# Generated by Django 5.0 on 2025-07-22 08:54

import django.core.validators
import django.db.models.deletion
import lib.erp_base.validators.people
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(null=True, unique=True, verbose_name='GUID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('extra_document', models.FileField(blank=True, max_length=127, null=True, upload_to='extra_documents', verbose_name='دستورات و مستندات')),
                ('phone_number', models.CharField(max_length=11, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('national_id', models.CharField(blank=True, max_length=10, null=True, validators=[lib.erp_base.validators.people.validate_national_id], verbose_name='کد ملی')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='نام خانوادگی')),
                ('birth_date', models.CharField(help_text='format: YYYY/MM/DD', max_length=10, null=True, validators=[django.core.validators.RegexValidator('\\d\\d\\d\\d\\/\\d\\d\\/\\d\\d', 'format : YYYY/MM/DD')], verbose_name='تاریخ تولد')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creations', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل',
                'verbose_name_plural': 'پروفایل\u200cها',
            },
        ),
    ]
