# Generated by Django 5.0 on 2025-10-05 14:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_guid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileKYCAttempt',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, null=True, unique=True, verbose_name='GUID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('extra_document', models.FileField(blank=True, max_length=127, null=True, upload_to='extra_documents', verbose_name='دستورات و مستندات')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_type', models.CharField(choices=[('SHAHKAR', 'Shahkar (phone/national match)'), ('VIDEO_SUBMIT', 'Video submit'), ('VIDEO_RESULT', 'Video result polling')], db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=16)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('request_payload', models.JSONField(blank=True, null=True)),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=64, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'KYC attempt',
                'verbose_name_plural': 'KYC attempts',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='auth_stage',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Signup'), (2, 'Identity Verified'), (3, 'Video Authentication Verified')], default=1, verbose_name='Authentication Stage'),
        ),
        migrations.AddField(
            model_name='profile',
            name='identity_verified_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when identity verification was completed', null=True, verbose_name='Identity Verified At'),
        ),
        migrations.AddField(
            model_name='profile',
            name='kyc_last_checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='KYC Last Checked At'),
        ),
        migrations.AddField(
            model_name='profile',
            name='kyc_status',
            field=models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('failed', 'Failed'), ('processing', 'Processing'), ('rejected', 'Rejected')], default=None, max_length=10, null=True, verbose_name='KYC Status'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_national_id_match_status',
            field=models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('failed', 'Failed'), ('processing', 'Processing'), ('rejected', 'Rejected')], default=None, max_length=10, null=True, verbose_name='Phone & National ID Match Status'),
        ),
        migrations.AddField(
            model_name='profile',
            name='video_submitted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when video KYC was submitted for verification', null=True, verbose_name='Video Submitted At'),
        ),
        migrations.AddField(
            model_name='profile',
            name='video_task_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Video Verification Task ID'),
        ),
        migrations.AddField(
            model_name='profile',
            name='video_verified_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when video verification result was received (accepted/rejected)', null=True, verbose_name='Video Verification Completed At'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^09\\d{9}$', 'Phone must start with 09 and be 11 digits')]),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['auth_stage'], name='profiles_pr_auth_st_56772c_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['kyc_status'], name='profiles_pr_kyc_sta_1c4d56_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['phone_national_id_match_status'], name='profiles_pr_phone_n_6d4013_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['video_task_id'], name='profiles_pr_video_t_598b47_idx'),
        ),
        migrations.AddField(
            model_name='profilekycattempt',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creations', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده'),
        ),
        migrations.AddField(
            model_name='profilekycattempt',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_attempts', to='profiles.profile'),
        ),
        migrations.AddIndex(
            model_name='profilekycattempt',
            index=models.Index(fields=['profile', 'attempt_type', 'created_at'], name='profiles_pr_profile_b1a9f6_idx'),
        ),
        migrations.AddIndex(
            model_name='profilekycattempt',
            index=models.Index(fields=['status', 'created_at'], name='profiles_pr_status_00f470_idx'),
        ),
        migrations.AddIndex(
            model_name='profilekycattempt',
            index=models.Index(fields=['external_id'], name='profiles_pr_externa_f3f756_idx'),
        ),
    ]
