# Generated by Django 5.0 on 2025-10-12 08:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_kycvideoasset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCVideoAsset2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, null=True, unique=True, verbose_name='GUID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('extra_document', models.FileField(blank=True, max_length=127, null=True, upload_to='extra_documents', verbose_name='دستورات و مستندات')),
                ('file', models.FileField(upload_to='kyc_videos/%Y/%m/%d/', verbose_name='فایل ویدئو')),
                ('sha256', models.CharField(blank=True, max_length=64, null=True, verbose_name='هش SHA256')),
                ('size', models.BigIntegerField(default=0, verbose_name='حجم (بایت)')),
                ('is_approved_copy', models.BooleanField(default=False, verbose_name='نسخهٔ مورد تأیید')),
                ('retention_until', models.DateTimeField(blank=True, null=True, verbose_name='نگهداشت تا')),
                ('created_by_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_assets', to='profiles.profilekycattempt', verbose_name='ایجاد شده توسط تلاش')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creations', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_video_assets', to='profiles.profile', verbose_name='پروفایل')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='KYCVideoAsset',
        ),
    ]
