# Generated by Django 5.0 on 2025-10-12 08:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_kycvideoasset2_delete_kycvideoasset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KYCVideoAsset2',
            new_name='KYCVideoAsset',
        ),
    ]
