# Generated by Django 5.0 on 2026-08-26 11:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_alter_kycvideoasset_guid_alter_profile_guid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycvideoasset',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='GUID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='GUID'),
        ),
        migrations.AlterField(
            model_name='profilekycattempt',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='GUID'),
        ),
    ]
