# Generated by Django 5.0 on 2025-09-07 13:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_unique_national_id_not_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, null=True, unique=True, verbose_name='GUID'),
        ),
    ]
