# Generated by Django 5.0 on 2025-10-06 11:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profilekycattempt_profile_auth_stage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='auth_stage',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Signup'), (2, 'Identity Verified'), (3, 'Video Authentication Verified')], default=1, verbose_name='مرحله احراز هویت'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.CharField(help_text='فرمت: YYYY/MM/DD', max_length=10, null=True, validators=[django.core.validators.RegexValidator('\\d\\d\\d\\d\\/\\d\\d\\/\\d\\d', 'فرمت باید YYYY/MM/DD باشد')], verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='identity_verified_at',
            field=models.DateTimeField(blank=True, help_text='زمانی که احراز هویت شاهکار با موفقیت انجام شد', null=True, verbose_name='زمان تایید هویت'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='kyc_last_checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخرین زمان بررسی KYC'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='kyc_status',
            field=models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('failed', 'Failed'), ('processing', 'Processing'), ('rejected', 'Rejected')], default=None, max_length=10, null=True, verbose_name='وضعیت KYC'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_national_id_match_status',
            field=models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('failed', 'Failed'), ('processing', 'Processing'), ('rejected', 'Rejected')], default=None, max_length=10, null=True, verbose_name='نتیجه شاهکار (تطابق موبایل/کدملی)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^09\\d{9}$', 'باید با 09 شروع شده و 11 رقم باشد')], verbose_name='شماره موبایل'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='video_submitted_at',
            field=models.DateTimeField(blank=True, help_text='زمان ارسال ویدئو برای احراز ویدئویی', null=True, verbose_name='زمان ارسال ویدئو'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='video_task_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='شناسه تسک ویدئو'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='video_verified_at',
            field=models.DateTimeField(blank=True, help_text='زمان ثبت نتیجه نهایی بررسی ویدئویی (قبول/رد)', null=True, verbose_name='زمان اتمام بررسی ویدئو'),
        ),
        migrations.CreateModel(
            name='ProfileKYCAttempt2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, null=True, unique=True, verbose_name='GUID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('extra_document', models.FileField(blank=True, max_length=127, null=True, upload_to='extra_documents', verbose_name='دستورات و مستندات')),
                ('id_fake', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('attempt_type', models.CharField(choices=[('SHAHKAR', 'Shahkar (phone/national match)'), ('VIDEO_SUBMIT', 'Video submit'), ('VIDEO_RESULT', 'Video result polling')], db_index=True, max_length=32, verbose_name='نوع تلاش')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=16, verbose_name='وضعیت')),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='شناسه خارجی')),
                ('request_payload', models.JSONField(blank=True, null=True, verbose_name='Payload درخواست')),
                ('response_payload', models.JSONField(blank=True, null=True, verbose_name='Payload پاسخ')),
                ('http_status', models.IntegerField(blank=True, null=True, verbose_name='کد HTTP')),
                ('error_code', models.CharField(blank=True, max_length=64, null=True, verbose_name='کد خطا')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='پیام خطا')),
                ('retry_count', models.PositiveIntegerField(default=0, verbose_name='تعداد تلاش مجدد')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان شروع')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creations', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_attempts', to='profiles.profile', verbose_name='پروفایل')),
            ],
            options={
                'verbose_name': 'تلاش KYC',
                'verbose_name_plural': 'تلاش\u200cهای KYC',
            },
        ),
        migrations.DeleteModel(
            name='ProfileKYCAttempt',
        ),
        migrations.AddIndex(
            model_name='profilekycattempt2',
            index=models.Index(fields=['profile', 'attempt_type', 'created_at'], name='profiles_pr_profile_e4d62d_idx'),
        ),
        migrations.AddIndex(
            model_name='profilekycattempt2',
            index=models.Index(fields=['status', 'created_at'], name='profiles_pr_status_18380f_idx'),
        ),
        migrations.AddIndex(
            model_name='profilekycattempt2',
            index=models.Index(fields=['external_id'], name='profiles_pr_externa_47d078_idx'),
        ),
    ]
