# Generated by Django 5.0 on 2025-10-11 08:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profilekycattempt_delete_profilekycattempt2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='profile',
            name='profiles_pr_kyc_sta_1c4d56_idx',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='kyc_last_checked_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='kyc_status',
        ),
        migrations.AddField(
            model_name='profile',
            name='video_auth_last_checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخرین زمان بررسی احراز هویت ویدئویی'),
        ),
        migrations.AddField(
            model_name='profile',
            name='video_auth_status',
            field=models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('failed', 'Failed'), ('processing', 'Processing'), ('rejected', 'Rejected')], default=None, max_length=10, null=True, verbose_name='وضعیت احراز هویت ویدئویی'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['video_auth_status'], name='profiles_pr_video_a_49a304_idx'),
        ),
        migrations.AddConstraint(
            model_name='profilekycattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('finished_at__isnull', True), ('status', 'PROCESSING')), fields=('profile', 'attempt_type'), name='uniq_processing_attempt_per_type_per_profile'),
        ),
    ]
