# Generated by Django 5.0 on 2025-10-11 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_remove_profile_profiles_pr_kyc_sta_1c4d56_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCVideoAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='kyc_videos/%Y/%m/%d/')),
                ('sha256', models.CharField(blank=True, max_length=64, null=True)),
                ('size', models.BigIntegerField(default=0)),
                ('is_approved_copy', models.BooleanField(default=False)),
                ('retention_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_assets', to='profiles.profilekycattempt')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_video_assets', to='profiles.profile')),
            ],
        ),
    ]
