# Generated by Django 5.0 on 2025-08-04 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0003_remove_merchantcontract_creator_and_more'),
        ('wallets', '0003_rename_merchant_confirmed_at_installmentrequest_store_confirmed_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MerchantContract',
        ),
    ]
