# Generated by Django 5.0 on 2026-05-12 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_guid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='guid',
            field=models.UUIDField(null=True, unique=True, verbose_name='GUID'),
        ),
    ]
