# Generated by Django 5.0 on 2026-08-26 11:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_guid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='GUID'),
        ),
    ]
