# Generated by Django 5.0 on 2025-08-04 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0003_remove_merchantcontract_creator_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(null=True, unique=True, verbose_name='GUID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('extra_document', models.FileField(blank=True, max_length=127, null=True, upload_to='extra_documents', verbose_name='دستورات و مستندات')),
                ('verification_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'کارشناس بررسی فروشگاه'), (2, 'نهایی\u200cشده'), (3, 'ردشده')], default=1)),
                ('store_reviewer_verification', models.IntegerField(choices=[(0, 'نامشخص'), (1, 'تأیید'), (2, 'عدم تأیید')], default=0, verbose_name='تأیید')),
                ('store_reviewer_note', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('store_reviewer_verification_time', models.DateTimeField(blank=True, null=True, verbose_name='زمان تأیید')),
                ('name', models.CharField(max_length=100, verbose_name='نام فروشگاه')),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='کد فروشگاه')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است؟')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creations', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='merchants.merchant', verbose_name='فروشنده')),
                ('store_reviewer_verifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_reviewer_store', to=settings.AUTH_USER_MODEL, verbose_name='تأییدکننده\u200c')),
            ],
            options={
                'verbose_name': 'فروشگاه',
                'verbose_name_plural': 'فروشگاه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='StoreApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_hash', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='هش کلید')),
                ('last_regenerated_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_key', to='store.store', verbose_name='فروشگاه')),
            ],
        ),
        migrations.CreateModel(
            name='StoreContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(null=True, unique=True, verbose_name='GUID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('extra_document', models.FileField(blank=True, max_length=127, null=True, upload_to='extra_documents', verbose_name='دستورات و مستندات')),
                ('verification_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'کارشناس بررسی قرارداد'), (2, 'نهایی\u200cشده'), (3, 'ردشده')], default=1)),
                ('contract_reviewer_verification', models.IntegerField(choices=[(0, 'نامشخص'), (1, 'تأیید'), (2, 'عدم تأیید')], default=0, verbose_name='تأیید')),
                ('contract_reviewer_note', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('contract_reviewer_verification_time', models.DateTimeField(blank=True, null=True, verbose_name='زمان تأیید')),
                ('max_credit_per_user', models.BigIntegerField(verbose_name='سقف اعتبار برای هر کاربر')),
                ('min_credit_per_user', models.BigIntegerField(default=0, verbose_name='حداقل اعتبار برای هر کاربر')),
                ('max_repayment_months', models.PositiveIntegerField(verbose_name='حداکثر مدت بازپرداخت (ماه)')),
                ('min_repayment_months', models.PositiveIntegerField(default=1, verbose_name='حداقل مدت بازپرداخت (ماه)')),
                ('allowed_period_months', models.JSONField(default=list, help_text='مثلاً [1, 2, 3]', verbose_name='پریودهای مجاز بازپرداخت (ماه)')),
                ('interest_rate', models.FloatField(default=0.0, help_text='نرخ بهره سالیانه (درصد)، به عنوان مثال: 18.0', verbose_name='نرخ بهره سالیانه (٪)')),
                ('callback_url', models.URLField(verbose_name='آدرس callback برای اطلاع تایید کاربر')),
                ('active', models.BooleanField(default=True, verbose_name='فعال')),
                ('contract_reviewer_verifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_reviewer_store_contract', to=settings.AUTH_USER_MODEL, verbose_name='تأییدکننده\u200c')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creations', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='store.store', verbose_name='فروشگاه')),
            ],
            options={
                'verbose_name': 'قرارداد فروشگاه',
                'verbose_name_plural': 'قراردادهای فروشگاه',
            },
        ),
        migrations.CreateModel(
            name='StoreUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(null=True, unique=True, verbose_name='GUID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('extra_document', models.FileField(blank=True, max_length=127, null=True, upload_to='extra_documents', verbose_name='دستورات و مستندات')),
                ('role', models.CharField(choices=[('manager', 'مدیر فروشگاه'), ('staff', 'کارمند'), ('accountant', 'حسابدار')], max_length=20, verbose_name='نقش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creations', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_users', to='store.store', verbose_name='فروشگاه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_roles', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کاربر فروشگاه',
                'verbose_name_plural': 'کاربران فروشگاه',
                'unique_together': {('store', 'user')},
            },
        ),
    ]
