# Generated by Django 5.0 on 2025-09-07 13:56

import store.models.store
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_storecontract_callback_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='عرض جغرافیایی'),
        ),
        migrations.AddField(
            model_name='store',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.store.store_logo_upload_path, validators=[store.models.store.validate_image_extension], verbose_name='لوگو فروشگاه'),
        ),
        migrations.AddField(
            model_name='store',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='طول جغرافیایی'),
        ),
        migrations.AddField(
            model_name='store',
            name='website_url',
            field=models.URLField(blank=True, verbose_name='لینک وب\u200cسایت فروشگاه'),
        ),
        migrations.AlterField(
            model_name='store',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, null=True, unique=True, verbose_name='GUID'),
        ),
        migrations.AlterField(
            model_name='storecontract',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, null=True, unique=True, verbose_name='GUID'),
        ),
        migrations.AlterField(
            model_name='storeuser',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, null=True, unique=True, verbose_name='GUID'),
        ),
    ]
