# Generated by Django 5.0 on 2025-08-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='کد فروشگاه'),
        ),
    ]
