# Generated by Django 5.0 on 2025-08-06 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_store_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storecontract',
            name='callback_url',
        ),
    ]
