# Generated by Django 5.0 on 2025-09-30 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_store_latitude_store_logo_store_longitude_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StoreContract',
        ),
    ]
