# Generated by Django 5.0 on 2026-05-12 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_delete_storecontract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='guid',
            field=models.UUIDField(null=True, unique=True, verbose_name='GUID'),
        ),
        migrations.AlterField(
            model_name='storeuser',
            name='guid',
            field=models.UUIDField(null=True, unique=True, verbose_name='GUID'),
        ),
    ]
