# Generated by Django 5.0 on 2026-08-26 11:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_store_guid_alter_storeuser_guid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='GUID'),
        ),
        migrations.AlterField(
            model_name='storeuser',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='GUID'),
        ),
    ]
