# Generated by Django 5.0 on 2026-05-12 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0003_alter_phoneotp_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneotp',
            name='guid',
            field=models.UUIDField(null=True, unique=True, verbose_name='GUID'),
        ),
    ]
