# Generated by Django 5.0 on 2025-07-22 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(null=True, unique=True, verbose_name='GUID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('extra_document', models.FileField(blank=True, max_length=127, null=True, upload_to='extra_documents', verbose_name='دستورات و مستندات')),
                ('shop_name', models.CharField(blank=True, max_length=100, verbose_name='نام فروشگاه')),
                ('shop_code', models.CharField(blank=True, max_length=20, verbose_name='کد فروشگاه')),
                ('shop_address', models.TextField(blank=True, verbose_name='آدرس فروشگاه')),
                ('license_number', models.CharField(blank=True, max_length=50, verbose_name='شماره مجوز')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creations', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merchant', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'فروشنده',
                'verbose_name_plural': 'فروشنده\u200cها',
            },
        ),
        migrations.CreateModel(
            name='MerchantApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_hash', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='هش کلید')),
                ('last_regenerated_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('merchant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_key', to='merchants.merchant', verbose_name='فروشنده')),
            ],
        ),
        migrations.CreateModel(
            name='MerchantCallbackSecret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(max_length=128, unique=True, verbose_name='کلید مخفی Callback')),
                ('last_regenerated_at', models.DateTimeField(blank=True, null=True, verbose_name='آخرین زمان تولید مجدد')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('merchant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='callback_secret', to='merchants.merchant', verbose_name='فروشنده')),
            ],
            options={
                'verbose_name': 'کلید Callback فروشنده',
                'verbose_name_plural': 'کلیدهای Callback فروشندگان',
            },
        ),
    ]
