# Generated by Django 5.0 on 2025-08-03 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(null=True, unique=True, verbose_name='GUID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('extra_document', models.FileField(blank=True, max_length=127, null=True, upload_to='extra_documents', verbose_name='دستورات و مستندات')),
                ('max_credit_per_user', models.BigIntegerField(verbose_name='سقف اعتبار برای هر کاربر')),
                ('min_credit_per_user', models.BigIntegerField(default=0, verbose_name='حداقل اعتبار برای هر کاربر')),
                ('max_repayment_months', models.PositiveIntegerField(verbose_name='حداکثر مدت بازپرداخت (ماه)')),
                ('min_repayment_months', models.PositiveIntegerField(default=1, verbose_name='حداقل مدت بازپرداخت (ماه)')),
                ('allowed_period_months', models.JSONField(default=list, help_text='مثلاً [1, 2, 3]', verbose_name='پریودهای مجاز بازپرداخت (ماه)')),
                ('interest_rate', models.FloatField(default=0.0, help_text='نرخ بهره سالیانه (درصد)، به عنوان مثال: 18.0', verbose_name='نرخ بهره سالیانه (٪)')),
                ('callback_url', models.URLField(blank=True, null=True, verbose_name='آدرس callback برای اطلاع تایید کاربر')),
                ('active', models.BooleanField(default=True, verbose_name='فعال')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creations', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='merchants.merchant', verbose_name='فروشنده')),
            ],
            options={
                'verbose_name': 'قرارداد فروشگاه',
                'verbose_name_plural': 'قراردادهای فروشگاه',
            },
        ),
        migrations.DeleteModel(
            name='MerchantCallbackSecret',
        ),
    ]
