# Generated by Django 5.0 on 2025-08-04 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0002_merchantcontract_delete_merchantcallbacksecret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchantcontract',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='merchantcontract',
            name='merchant',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='license_number',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='shop_address',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='shop_code',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='shop_name',
        ),
        migrations.DeleteModel(
            name='MerchantApiKey',
        ),
    ]
