# Generated by Django 5.0 on 2025-09-07 13:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0004_delete_merchantcontract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, null=True, unique=True, verbose_name='GUID'),
        ),
    ]
