# Generated by Django 5.0 on 2026-05-12 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='guid',
            field=models.UUIDField(null=True, unique=True, verbose_name='GUID'),
        ),
    ]
