# Generated by Django 5.0 on 2025-09-30 13:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketcategory',
            options={'ordering': ['id'], 'verbose_name': 'دسته\u200cبندی تیکت', 'verbose_name_plural': 'دسته\u200cبندی\u200cهای تیکت'},
        ),
        migrations.AddIndex(
            model_name='ticketmessage',
            index=models.Index(fields=['ticket', 'id'], name='tickets_tic_ticket__3ca4a7_idx'),
        ),
    ]
