# Generated by Django 5.0 on 2025-07-22 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(null=True, unique=True, verbose_name='GUID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('extra_document', models.FileField(blank=True, max_length=127, null=True, upload_to='extra_documents', verbose_name='دستورات و مستندات')),
                ('status', models.CharField(choices=[('created', 'در انتظار پرداخت کاربر'), ('awaiting_merchant', 'در انتظار تایید فروشنده'), ('completed', 'پرداخت نهایی شده'), ('cancelled', 'لغو شده'), ('expired', 'منقضی شده')], default='created', max_length=32, verbose_name='وضعیت')),
                ('reference_code', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='کد پیگیری')),
                ('amount', models.BigIntegerField(verbose_name='مبلغ')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='توضیحات')),
                ('return_url', models.URLField(verbose_name='آدرس بازگشت (return_url)')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creations', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to=settings.AUTH_USER_MODEL, verbose_name='فروشنده درخواست\u200cدهنده')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='successful_payments', to=settings.AUTH_USER_MODEL, verbose_name='پرداخت\u200cکننده')),
            ],
            options={
                'verbose_name': 'درخواست پرداخت',
                'verbose_name_plural': 'درخواست\u200cهای پرداخت',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(null=True, unique=True, verbose_name='GUID')),
                ('extra_document', models.FileField(blank=True, max_length=127, null=True, upload_to='extra_documents', verbose_name='دستورات و مستندات')),
                ('owner_type', models.CharField(choices=[('customer', 'مشتری'), ('merchant', 'فروشنده'), ('system', 'سیستم')], max_length=20, verbose_name='نوع کاربر')),
                ('kind', models.CharField(choices=[('micro_credit', 'اعتباری خرد'), ('cash', 'نقدی'), ('credit', 'اعتباری'), ('cashback', 'بازگشت پول'), ('merchant_gateway', 'درگاه فروشگاه'), ('escrow', 'escrow')], max_length=20, verbose_name='نوع')),
                ('balance', models.BigIntegerField(default=0, verbose_name='مبلغ')),
                ('reserved_balance', models.BigIntegerField(default=0, verbose_name='مبلغ رزروشده')),
                ('wallet_number', models.CharField(blank=True, db_index=True, max_length=12, unique=True, verbose_name='شماره کیف پول')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creations', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کیف پول',
                'verbose_name_plural': 'کیف پول\u200cها',
                'unique_together': {('user', 'owner_type', 'kind')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(null=True, unique=True, verbose_name='GUID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('extra_document', models.FileField(blank=True, max_length=127, null=True, upload_to='extra_documents', verbose_name='دستورات و مستندات')),
                ('reference_code', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='کد پیگیری')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید'), ('success', 'موفق'), ('failed', 'ناموفق'), ('reversed', 'برگشت\u200cخورده')], default='pending', max_length=16, verbose_name='وضعیت')),
                ('amount', models.BigIntegerField(verbose_name='مبلغ')),
                ('description', models.TextField(blank=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creations', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('payment_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallets.paymentrequest', verbose_name='مبلغ')),
                ('from_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transactions', to='wallets.wallet', verbose_name='از کیف پول')),
                ('to_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transactions', to='wallets.wallet', verbose_name='به کیف پول')),
            ],
            options={
                'verbose_name': 'تراکنش کیف پول',
                'verbose_name_plural': 'تراکنش\u200cهای کیف پول',
            },
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='paid_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wallets.wallet', verbose_name='کیف پول پرداخت\u200cکننده'),
        ),
        migrations.CreateModel(
            name='WalletTransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(null=True, unique=True, verbose_name='GUID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('extra_document', models.FileField(blank=True, max_length=127, null=True, upload_to='extra_documents', verbose_name='دستورات و مستندات')),
                ('reference_code', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='کد پیگیری')),
                ('receiver_phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره موبایل مقصد')),
                ('amount', models.BigIntegerField(verbose_name='مبلغ')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('pending_confirmation', 'در انتظار تایید گیرنده'), ('success', 'انجام شده'), ('rejected', 'رد شده'), ('expired', 'منقضی شده')], default='pending_confirmation', max_length=32, verbose_name='وضعیت')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='انقضا')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creations', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('receiver_wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_transfers', to='wallets.wallet', verbose_name='کیف مقصد')),
                ('sender_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transfers', to='wallets.wallet', verbose_name='کیف مبدا')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_request', to='wallets.transaction', verbose_name='تراکنش')),
            ],
            options={
                'verbose_name': 'درخواست انتقال کیف',
                'verbose_name_plural': 'درخواست\u200cهای انتقال کیف',
                'indexes': [models.Index(fields=['sender_wallet'], name='wallets_wal_sender__ca65b7_idx'), models.Index(fields=['receiver_wallet'], name='wallets_wal_receive_c4ea50_idx'), models.Index(fields=['receiver_phone_number'], name='wallets_wal_receive_f65db1_idx'), models.Index(fields=['reference_code'], name='wallets_wal_referen_133dd9_idx'), models.Index(fields=['status'], name='wallets_wal_status_0afd65_idx')],
            },
        ),
    ]
