# Generated by Django 5.0 on 2025-08-04 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('wallets', '0002_installmentplan_installment_installmentrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='installmentrequest',
            old_name='merchant_confirmed_at',
            new_name='store_confirmed_at',
        ),
        migrations.RemoveField(
            model_name='installmentrequest',
            name='merchant',
        ),
        migrations.RemoveField(
            model_name='paymentrequest',
            name='merchant',
        ),
        migrations.AddField(
            model_name='installmentrequest',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installment_requests', to='store.store', verbose_name='فروشگاه'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to='store.store', verbose_name='فروشگاه درخواست\u200cدهنده'),
        ),
        migrations.AlterField(
            model_name='installmentrequest',
            name='confirmed_amount',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='مبلغ تایید شده توسط مشتری'),
        ),
        migrations.AlterField(
            model_name='installmentrequest',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installment_requests', to='store.storecontract', verbose_name='قرارداد فروشگاه'),
        ),
        migrations.AlterField(
            model_name='installmentrequest',
            name='return_url',
            field=models.URLField(verbose_name='آدرس بازگشت'),
        ),
    ]
