# Generated by Django 5.0 on 2025-08-06 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_rename_merchant_confirmed_at_installmentrequest_store_confirmed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installmentrequest',
            name='return_url',
        ),
    ]
