# Generated by Django 5.0 on 2025-08-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0006_remove_installmentrequest_credit_limit_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='installmentrequest',
            old_name='proposal_amount',
            new_name='store_proposed_amount',
        ),
        migrations.RemoveField(
            model_name='installmentrequest',
            name='confirmed_amount',
        ),
        migrations.AddField(
            model_name='installmentrequest',
            name='cancel_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='دلیل لغو'),
        ),
        migrations.AddField(
            model_name='installmentrequest',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان لغو'),
        ),
        migrations.AddField(
            model_name='installmentrequest',
            name='evaluated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان انجام اعتبارسنجی'),
        ),
        migrations.AddField(
            model_name='installmentrequest',
            name='requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان ثبت درخواست کاربر'),
        ),
        migrations.AddField(
            model_name='installmentrequest',
            name='system_approved_amount',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='مبلغ تاییدشده توسط سیستم (نتیجه اعتبارسنجی)'),
        ),
        migrations.AddField(
            model_name='installmentrequest',
            name='user_requested_amount',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='مبلغ درخواستی کاربر (قبل از اعتبارسنجی)'),
        ),
        migrations.AlterField(
            model_name='installmentrequest',
            name='status',
            field=models.CharField(choices=[('created', 'در انتظار ورود شرایط توسط کاربر'), ('underwriting', 'در انتظار نتیجه اعتبارسنجی'), ('validated', 'اعتبارسنجی شد؛ منتظر تایید کاربر'), ('awaiting_merchant', 'در انتظار تایید فروشنده'), ('completed', 'تایید نهایی انجام شد'), ('cancelled', 'لغو شده'), ('rejected', 'رد شده')], default='created', max_length=32, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='installmentrequest',
            name='store_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان تایید فروشگاه'),
        ),
        migrations.AlterField(
            model_name='installmentrequest',
            name='user_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان تایید کاربر'),
        ),
    ]
