# Generated by Django 5.0 on 2025-09-07 13:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0007_rename_proposal_amount_installmentrequest_store_proposed_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installment',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, null=True, unique=True, verbose_name='GUID'),
        ),
        migrations.AlterField(
            model_name='installmentplan',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, null=True, unique=True, verbose_name='GUID'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, null=True, unique=True, verbose_name='GUID'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, null=True, unique=True, verbose_name='GUID'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallets.paymentrequest', verbose_name='درخواست پرداخت'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, null=True, unique=True, verbose_name='GUID'),
        ),
        migrations.AlterField(
            model_name='wallettransferrequest',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, null=True, unique=True, verbose_name='GUID'),
        ),
        migrations.DeleteModel(
            name='InstallmentRequest',
        ),
    ]
