# Generated by Django 5.0 on 2025-09-24 07:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_store_latitude_store_logo_store_longitude_and_more'),
        ('wallets', '0008_alter_installment_guid_alter_installmentplan_guid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='external_guid',
            field=models.CharField(blank=True, help_text='شناسهٔ یکتا از سمت فروشگاه/سیستم بیرونی', max_length=64, null=True, verbose_name='شناسه بیرونی (external_guid)'),
        ),
        migrations.AddIndex(
            model_name='paymentrequest',
            index=models.Index(fields=['status'], name='pr_status_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrequest',
            index=models.Index(fields=['expires_at'], name='pr_expires_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrequest',
            index=models.Index(fields=['store', 'status'], name='pr_store_status_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrequest',
            index=models.Index(fields=['reference_code'], name='pr_ref_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrequest',
            index=models.Index(fields=['store', 'external_guid'], name='pr_store_ext_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('external_guid__isnull', False)), fields=('store', 'external_guid'), name='uniq_store_external_guid'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('kind__in', ['cash', 'cashback']), _negated=True), ('balance__gte', 0), _connector='OR'), name='balance_non_negative_for_cash_like'),
        ),
    ]
