# Generated by Django 5.0 on 2025-09-28 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_guid'),
        ('wallets', '0009_paymentrequest_external_guid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='customer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to='customers.customer', verbose_name='مشتری'),
            preserve_default=False,
        ),
    ]
