# Generated by Django 5.0 on 2025-10-01 12:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0011_installment_inst_plan_due_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='created_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ددلاین فاز CREATED'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='merchant_confirm_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ددلاین تایید مرچنت'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='purpose',
            field=models.CharField(choices=[('escrow_debit', 'انتقال به امانی (Escrow)'), ('settlement', 'تسویه با فروشنده'), ('reversal', 'بازگشت وجه')], db_index=True, max_length=32, null=True, verbose_name='نوع عملیات'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['payment_request', 'purpose', 'status'], name='trx_pr_purpose_status_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['from_wallet_id', 'to_wallet_id'], name='trx_from_to_idx'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='trx_amount_gt_zero'),
        ),
    ]
