# Generated by Django 5.0 on 2025-08-03 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('merchants', '0002_merchantcontract_delete_merchantcallbacksecret'),
        ('wallets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(null=True, unique=True, verbose_name='GUID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('extra_document', models.FileField(blank=True, max_length=127, null=True, upload_to='extra_documents', verbose_name='دستورات و مستندات')),
                ('source_type', models.CharField(choices=[('bnpl', 'درخواست فروشگاه (BNPL)'), ('payment_request', 'پرداخت با اعتبار داخلی')], max_length=32, verbose_name='نوع منبع')),
                ('source_object_id', models.PositiveBigIntegerField(verbose_name='شناسه مرجع منبع')),
                ('total_amount', models.BigIntegerField(verbose_name='مبلغ کل قابل پرداخت')),
                ('duration_months', models.PositiveIntegerField(verbose_name='مدت بازپرداخت (ماه)')),
                ('period_months', models.PositiveIntegerField(verbose_name='پریود پرداخت اقساط (ماه)')),
                ('interest_rate', models.FloatField(verbose_name='نرخ بهره سالیانه (٪)')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_by', models.CharField(default='system', max_length=32, verbose_name='ایجاد شده توسط')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان بستن')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('completed', 'پرداخت\u200cشده کامل'), ('cancelled', 'لغو شده')], default='active', max_length=16, verbose_name='وضعیت')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creations', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('initial_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installment_plans', to='wallets.transaction', verbose_name='تراکنش اولیه مرتبط')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_plans', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'برنامه اقساطی',
                'verbose_name_plural': 'برنامه\u200cهای اقساطی',
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(null=True, unique=True, verbose_name='GUID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('extra_document', models.FileField(blank=True, max_length=127, null=True, upload_to='extra_documents', verbose_name='دستورات و مستندات')),
                ('due_date', models.DateField(verbose_name='تاریخ سررسید')),
                ('amount', models.BigIntegerField(verbose_name='مبلغ قسط')),
                ('amount_paid', models.BigIntegerField(default=0, verbose_name='مبلغ پرداخت\u200cشده')),
                ('penalty_amount', models.BigIntegerField(default=0, verbose_name='جریمه پرداخت\u200cشده')),
                ('status', models.CharField(choices=[('unpaid', 'پرداخت\u200cنشده'), ('paid', 'پرداخت\u200cشده'), ('overdue', 'سررسید گذشته')], default='unpaid', max_length=16, verbose_name='وضعیت')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پرداخت')),
                ('note', models.TextField(blank=True, verbose_name='یادداشت')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creations', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installments', to='wallets.transaction', verbose_name='تراکنش پرداخت')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='wallets.installmentplan', verbose_name='برنامه اقساط')),
            ],
            options={
                'verbose_name': 'قسط',
                'verbose_name_plural': 'اقساط',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='InstallmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(null=True, unique=True, verbose_name='GUID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('extra_document', models.FileField(blank=True, max_length=127, null=True, upload_to='extra_documents', verbose_name='دستورات و مستندات')),
                ('reference_code', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='کد پیگیری')),
                ('national_id', models.CharField(max_length=10, verbose_name='کد ملی')),
                ('proposal_amount', models.BigIntegerField(verbose_name='مبلغ پیشنهادی فروشگاه')),
                ('credit_limit_amount', models.BigIntegerField(verbose_name='سقف اعتبار قابل ارائه')),
                ('confirmed_amount', models.BigIntegerField(blank=True, null=True, verbose_name='مبلغ تایید شده توسط کاربر')),
                ('duration_months', models.PositiveIntegerField(blank=True, null=True, verbose_name='مدت بازپرداخت (ماه)')),
                ('period_months', models.PositiveIntegerField(blank=True, null=True, verbose_name='پریود بازپرداخت (ماه)')),
                ('return_url', models.URLField(verbose_name='آدرس بازگشت (return_url)')),
                ('status', models.CharField(choices=[('created', 'در انتظار تایید کاربر'), ('awaiting_merchant', 'در انتظار تایید فروشنده'), ('completed', 'تایید نهایی انجام شد'), ('cancelled', 'لغو شده'), ('rejected', 'رد شده')], default='created', max_length=32, verbose_name='وضعیت')),
                ('user_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('merchant_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installment_requests', to='merchants.merchantcontract', verbose_name='قرارداد استفاده شده')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creations', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_requests', to='customers.customer', verbose_name='مشتری')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_requests', to='merchants.merchant', verbose_name='فروشگاه')),
            ],
            options={
                'verbose_name': 'درخواست خرید اقساطی',
                'verbose_name_plural': 'درخواست\u200cهای خرید اقساطی',
            },
        ),
    ]
