# Generated by Django 5.0 on 2025-08-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0004_remove_installmentrequest_return_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='installmentrequest',
            name='external_guid',
            field=models.CharField(default='', help_text='GUID اختصاصی ارسال\u200cشده از سیستم فروشگاه', max_length=64, verbose_name='شناسه خارجی (سیستم فروشگاه)'),
            preserve_default=False,
        ),
    ]
