# Generated by Django 5.0 on 2025-08-09 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0005_installmentrequest_external_guid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installmentrequest',
            name='credit_limit_amount',
        ),
    ]
