# Generated by Django 5.0 on 2025-09-29 11:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_guid'),
        ('store', '0004_store_latitude_store_logo_store_longitude_and_more'),
        ('wallets', '0010_paymentrequest_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='installment',
            index=models.Index(fields=['plan', 'due_date'], name='inst_plan_due_idx'),
        ),
        migrations.AddIndex(
            model_name='installment',
            index=models.Index(fields=['status'], name='inst_status_idx'),
        ),
        migrations.AddIndex(
            model_name='installmentplan',
            index=models.Index(fields=['user', '-created_at'], name='iplan_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrequest',
            index=models.Index(fields=['customer', '-created_at'], name='pr_cust_created_idx'),
        ),
    ]
