# Generated by Django 4.2.25 on 2026-04-05 11:33

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('customers', '0002_alter_customer_guid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallets', '0012_paymentrequest_created_expires_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False,
                    verbose_name='ID'
                )),
                ('guid', models.UUIDField(
                    default=uuid.uuid4, null=True, unique=True, verbose_name='GUID'
                )),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('extra_document', models.FileField(
                    blank=True, max_length=127, null=True, upload_to='extra_documents',
                    verbose_name='دستورات و مستندات'
                )),
                ('amount', models.BigIntegerField(verbose_name='مبلغ')),
                ('method', models.CharField(
                    choices=[('cash', 'نقدی'), ('credit', 'اعتباری')], max_length=16,
                    verbose_name='روش پرداخت'
                )),
                ('flow_type', models.CharField(
                    choices=[('online', 'آنلاین'), ('qr_pos', 'حضوری QR')],
                    max_length=16, verbose_name='نوع جریان'
                )),
                ('status', models.CharField(
                    choices=[('created', 'ایجاد شده'), ('authorized', 'مجاز/هولد شده'),
                             ('awaiting_merchant', 'در انتظار تایید فروشگاه'),
                             ('completed', 'تکمیل شده'), ('cancelled', 'لغو شده'),
                             ('expired', 'منقضی شده'), ('failed', 'ناموفق')],
                    db_index=True, default='created', max_length=32,
                    verbose_name='وضعیت'
                )),
                ('reference_code', models.CharField(
                    blank=True, max_length=20, null=True, unique=True,
                    verbose_name='کد پیگیری'
                )),
                ('authorization_expires_at', models.DateTimeField(
                    blank=True, null=True, verbose_name='انقضای مجوز/هولد'
                )),
                ('merchant_confirm_expires_at', models.DateTimeField(
                    blank=True, null=True, verbose_name='انقضای تایید فروشگاه'
                )),
                ('completed_at', models.DateTimeField(
                    blank=True, null=True, verbose_name='زمان تکمیل'
                )),
                ('cancelled_at',
                 models.DateTimeField(blank=True, null=True, verbose_name='زمان لغو')),
                ('expired_at', models.DateTimeField(
                    blank=True, null=True, verbose_name='زمان انقضا'
                )),
                ('failure_reason',
                 models.CharField(blank=True, max_length=255, verbose_name='دلیل خطا')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
            },
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='flow_type',
            field=models.CharField(
                choices=[('online', 'آنلاین'), ('qr_pos', 'حضوری QR')],
                default='online', max_length=16, verbose_name='نوع جریان'
            ),
        ),
        migrations.AddField(
            model_name='transaction',
            name='related_transaction',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='child_transactions', to='wallets.transaction',
                verbose_name='تراکنش مرتبط'
            ),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='created_expires_at',
            field=models.DateTimeField(
                blank=True, null=True, verbose_name='ددلاین فاز created'
            ),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='customer',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                related_name='payment_requests', to='customers.customer',
                verbose_name='مشتری'
            ),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='external_guid',
            field=models.CharField(
                blank=True, help_text='شناسه یکتای سمت فروشگاه/سیستم بیرونی',
                max_length=64, null=True, verbose_name='شناسه بیرونی'
            ),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='merchant_confirm_expires_at',
            field=models.DateTimeField(
                blank=True, null=True, verbose_name='ددلاین تایید فروشگاه'
            ),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='return_url',
            field=models.URLField(verbose_name='آدرس بازگشت'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='purpose',
            field=models.CharField(
                blank=True, choices=[('escrow_debit', 'انتقال به امانی (Escrow)'),
                                     ('settlement', 'تسویه با فروشنده'),
                                     ('reversal', 'بازگشت وجه')], db_index=True,
                max_length=32, null=True, verbose_name='نوع عملیات'
            ),
        ),
        migrations.AddIndex(
            model_name='paymentrequest',
            index=models.Index(
                fields=['flow_type', 'status'], name='pr_flow_status_idx'
            ),
        ),
        migrations.AddField(
            model_name='payment',
            name='creator',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='%(class)s_creations', to=settings.AUTH_USER_MODEL,
                verbose_name='ایجاد کننده'
            ),
        ),
        migrations.AddField(
            model_name='payment',
            name='payer',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='payments',
                to=settings.AUTH_USER_MODEL, verbose_name='پرداخت\u200cکننده'
            ),
        ),
        migrations.AddField(
            model_name='payment',
            name='payer_wallet',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='payments', to='wallets.wallet',
                verbose_name='کیف پول پرداخت\u200cکننده'
            ),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_request',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='payments',
                to='wallets.paymentrequest', verbose_name='درخواست پرداخت'
            ),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='transactions', to='wallets.payment',
                verbose_name='پرداخت مرتبط'
            ),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(
                fields=['payment', 'purpose', 'status'],
                name='trx_payment_purpose_status_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(
                fields=['payment_request', 'status'], name='pay_pr_status_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payer', 'status'], name='pay_payer_status_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(
                fields=['flow_type', 'status'], name='pay_flow_status_idx'
            ),
        ),
    ]
