# Generated by Django 4.2.25 on 2026-04-06 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallets', '0013_payment_paymentrequest_cancelled_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, null=True, unique=True, verbose_name='GUID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('extra_document', models.FileField(blank=True, max_length=127, null=True, upload_to='extra_documents', verbose_name='دستورات و مستندات')),
                ('event_type', models.CharField(choices=[('payment_request_created', 'درخواست پرداخت ایجاد شد'), ('payment_authorized', 'پرداخت مجاز شد'), ('awaiting_merchant', 'در انتظار تایید فروشگاه'), ('payment_settled', 'تسویه انجام شد'), ('payment_completed', 'پرداخت تکمیل شد'), ('payment_cancelled', 'پرداخت لغو شد'), ('payment_expired', 'پرداخت منقضی شد'), ('payment_rollback', 'بازگشت وجه/آزادسازی انجام شد'), ('payment_verify_requested', 'درخواست نهایی\u200cسازی ثبت شد')], db_index=True, max_length=64, verbose_name='نوع رویداد')),
                ('from_status', models.CharField(blank=True, max_length=32, null=True, verbose_name='وضعیت قبلی')),
                ('to_status', models.CharField(blank=True, max_length=32, null=True, verbose_name='وضعیت جدید')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='توضیحات')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='داده تکمیلی')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_events', to=settings.AUTH_USER_MODEL, verbose_name='کاربر عامل')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creations', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='wallets.payment', verbose_name='پرداخت')),
                ('payment_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='wallets.paymentrequest', verbose_name='درخواست پرداخت')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_events', to='wallets.transaction', verbose_name='تراکنش مرتبط')),
            ],
            options={
                'verbose_name': 'رویداد پرداخت',
                'verbose_name_plural': 'رویدادهای پرداخت',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['payment_request', 'event_type'], name='payevt_pr_type_idx'), models.Index(fields=['payment', 'event_type'], name='payevt_pay_type_idx'), models.Index(fields=['event_type', 'created_at'], name='payevt_type_created_idx')],
            },
        ),
    ]
