# Generated by Django 4.2.25 on 2026-04-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0014_paymentevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='return_url',
            field=models.URLField(blank=True, null=True, verbose_name='آدرس بازگشت'),
        ),
    ]
