# Generated by Django 4.2.25 on 2026-04-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0015_alter_paymentrequest_return_url'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['created', 'authorized', 'awaiting_merchant'])), fields=('payment_request',), name='uniq_active_payment_per_request'),
        ),
    ]
