# Generated by Django 5.0 on 2026-05-12 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0016_payment_uniq_active_payment_per_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installment',
            name='guid',
            field=models.UUIDField(null=True, unique=True, verbose_name='GUID'),
        ),
        migrations.AlterField(
            model_name='installmentplan',
            name='guid',
            field=models.UUIDField(null=True, unique=True, verbose_name='GUID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='guid',
            field=models.UUIDField(null=True, unique=True, verbose_name='GUID'),
        ),
        migrations.AlterField(
            model_name='paymentevent',
            name='guid',
            field=models.UUIDField(null=True, unique=True, verbose_name='GUID'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='guid',
            field=models.UUIDField(null=True, unique=True, verbose_name='GUID'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='guid',
            field=models.UUIDField(null=True, unique=True, verbose_name='GUID'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='guid',
            field=models.UUIDField(null=True, unique=True, verbose_name='GUID'),
        ),
        migrations.AlterField(
            model_name='wallettransferrequest',
            name='guid',
            field=models.UUIDField(null=True, unique=True, verbose_name='GUID'),
        ),
    ]
