# Generated by Django 5.0 on 2026-08-26 11:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0017_alter_installment_guid_alter_installmentplan_guid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installment',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='GUID'),
        ),
        migrations.AlterField(
            model_name='installmentplan',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='GUID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='GUID'),
        ),
        migrations.AlterField(
            model_name='paymentevent',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='GUID'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='GUID'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='GUID'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='GUID'),
        ),
        migrations.AlterField(
            model_name='wallettransferrequest',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='GUID'),
        ),
    ]
