# Generated by Django 5.0 on 2025-10-01 12:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0001_initial'),
        ('wallets', '0012_paymentrequest_created_expires_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, null=True, unique=True, verbose_name='GUID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('extra_document', models.FileField(blank=True, max_length=127, null=True, upload_to='extra_documents', verbose_name='دستورات و مستندات')),
                ('amount', models.BigIntegerField(verbose_name='مبلغ')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('settled', 'نهایی\u200cشده'), ('released', 'آزادشده'), ('expired', 'منقضی')], db_index=True, default='active', max_length=16)),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='انقضا')),
                ('reference_code', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='کد پیگیری')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creations', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('payment_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_authorizations', to='wallets.paymentrequest', verbose_name='درخواست پرداخت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_authorizations', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'هولد اعتباری',
                'verbose_name_plural': 'هولدهای اعتباری',
                'indexes': [models.Index(fields=['user', 'status'], name='auth_user_status_idx'), models.Index(fields=['expires_at'], name='auth_expires_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='creditauthorization',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('payment_request',), name='uniq_active_auth_per_payment_request'),
        ),
        migrations.AddConstraint(
            model_name='creditauthorization',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='auth_amount_gt_zero'),
        ),
    ]
