# Generated by Django 5.0 on 2025-10-11 08:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0002_creditauthorization_and_more'),
        ('profiles', '0007_remove_profile_profiles_pr_kyc_sta_1c4d56_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRiskReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, null=True, unique=True, verbose_name='GUID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('extra_document', models.FileField(blank=True, max_length=127, null=True, upload_to='extra_documents', verbose_name='دستورات و مستندات')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار'), ('OTP_SENT', 'کد ارسال شده'), ('IN_PROCESSING', 'در حال پردازش'), ('COMPLETED', 'تکمیل شده'), ('FAILED', 'ناموفق'), ('EXPIRED', 'منقضی شده')], db_index=True, default='PENDING', max_length=20, verbose_name='وضعیت')),
                ('otp_unique_id', models.CharField(blank=True, help_text='Unique ID from OTP send request', max_length=100, null=True, verbose_name='شناسه یکتای OTP')),
                ('otp_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال OTP')),
                ('report_unique_id', models.CharField(blank=True, db_index=True, help_text='Unique ID from report request', max_length=100, null=True, unique=True, verbose_name='شناسه یکتای گزارش')),
                ('report_requested_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان درخواست گزارش')),
                ('credit_score', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='امتیاز اعتباری')),
                ('risk_level', models.CharField(blank=True, choices=[('A1', 'ریسک بسیار پایین'), ('A2', 'ریسک پایین'), ('B1', 'ریسک کم'), ('B2', 'ریسک متوسط پایین'), ('C1', 'ریسک متوسط'), ('C2', 'ریسک متوسط بالا'), ('D', 'ریسک بالا'), ('E', 'ریسک بسیار بالا'), ('UNKNOWN', 'نامشخص')], db_index=True, max_length=20, null=True, verbose_name='سطح ریسک')),
                ('grade_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='توضیحات درجه ریسک')),
                ('report_data', models.JSONField(blank=True, help_text='Complete JSON report from external service', null=True, verbose_name='داده\u200cهای کامل گزارش')),
                ('national_code', models.CharField(db_index=True, max_length=10, verbose_name='کد ملی')),
                ('mobile_number', models.CharField(max_length=11, verbose_name='شماره موبایل')),
                ('report_timestamp', models.CharField(blank=True, max_length=50, null=True, verbose_name='تاریخ و زمان گزارش (از سرویس)')),
                ('report_types', models.JSONField(blank=True, help_text='List of report types included (e.g., Base, Score, Tax)', null=True, verbose_name='انواع گزارش')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='پیام خطا')),
                ('error_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد خطا')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تکمیل')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creations', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_risk_reports', to='profiles.profile', verbose_name='پروفایل')),
            ],
            options={
                'verbose_name': 'گزارش ریسک وام',
                'verbose_name_plural': 'گزارش\u200cهای ریسک وام',
                'db_table': 'credit_loan_risk_report',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['profile', '-created_at'], name='credit_loan_profile_e39f19_idx'), models.Index(fields=['status', '-created_at'], name='credit_loan_status_e56b64_idx'), models.Index(fields=['credit_score'], name='credit_loan_credit__a891df_idx')],
            },
        ),
    ]
