# Generated by Django 4.2.25 on 2026-04-05 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('wallets', '0013_payment_paymentrequest_cancelled_at_and_more'),
        ('credit', '0003_loanriskreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditauthorization',
            name='payment',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                related_name='credit_authorizations', to='wallets.payment',
                verbose_name='پرداخت'
            ),
        ),
        migrations.AddField(
            model_name='statementline',
            name='payment',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='statement_lines', to='wallets.payment',
                verbose_name='پرداخت مرتبط'
            ),
        ),
        migrations.AddField(
            model_name='statementline',
            name='payment_request',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='statement_lines', to='wallets.paymentrequest',
                verbose_name='درخواست پرداخت مرتبط'
            ),
        ),
        migrations.AlterField(
            model_name='loanriskreport',
            name='risk_level',
            field=models.CharField(
                blank=True, choices=[('A1', 'ریسک بسیار پایین (A1)'),
                                     ('A2', 'ریسک بسیار پایین (A2)'),
                                     ('A3', 'ریسک بسیار پایین (A3)'),
                                     ('B1', 'ریسک پایین (B1)'),
                                     ('B2', 'ریسک پایین (B2)'),
                                     ('B3', 'ریسک پایین (B3)'),
                                     ('C1', 'ریسک متوسط (C1)'),
                                     ('C2', 'ریسک متوسط (C2)'),
                                     ('C3', 'ریسک متوسط (C3)'), ('D', 'ریسک بالا (D)'),
                                     ('E', 'ریسک بسیار بالا (E)'),
                                     ('UNKNOWN', 'نامشخص')], db_index=True,
                max_length=20, null=True, verbose_name='سطح ریسک'
            ),
        ),
        migrations.AlterField(
            model_name='statement',
            name='year',
            field=models.SmallIntegerField(
                choices=[(1405, '1405'), (1404, '1404')], verbose_name='سال'
            ),
        ),
        migrations.AddIndex(
            model_name='creditauthorization',
            index=models.Index(
                fields=['payment', 'status'], name='auth_payment_status_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='statementline',
            index=models.Index(fields=['payment'], name='stl_payment_idx'),
        ),
        migrations.AddIndex(
            model_name='statementline',
            index=models.Index(fields=['payment_request'], name='stl_pr_idx'),
        ),
    ]
