# Generated by Django 5.0 on 2026-05-12 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0004_creditauthorization_payment_statementline_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditauthorization',
            name='guid',
            field=models.UUIDField(null=True, unique=True, verbose_name='GUID'),
        ),
        migrations.AlterField(
            model_name='creditlimit',
            name='guid',
            field=models.UUIDField(null=True, unique=True, verbose_name='GUID'),
        ),
        migrations.AlterField(
            model_name='loanriskreport',
            name='guid',
            field=models.UUIDField(null=True, unique=True, verbose_name='GUID'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='guid',
            field=models.UUIDField(null=True, unique=True, verbose_name='GUID'),
        ),
        migrations.AlterField(
            model_name='statementline',
            name='guid',
            field=models.UUIDField(null=True, unique=True, verbose_name='GUID'),
        ),
    ]
