# Generated by Django 5.0 on 2026-08-26 11:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_alter_bank_guid_alter_bankcard_guid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='GUID'),
        ),
        migrations.AlterField(
            model_name='bankcard',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='GUID'),
        ),
    ]
